
import __ASTRO_IMAGE_IMPORT_3JFh3 from "./intro-studio.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fintro.md";
import __ASTRO_IMAGE_IMPORT_Z23kbgg from "/src/images/projects/back-to-the-start-website.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fback-to-the-start.md";
import __ASTRO_IMAGE_IMPORT_Z1Qx4O0 from "/src/images/projects/capital-city-transportation-website.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fcapital-city-transportation.md";
import __ASTRO_IMAGE_IMPORT_WTTUo from "/src/images/projects/elevated-photo-booths-website.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Felevated-photo-booths.md";
import __ASTRO_IMAGE_IMPORT_Z1Gk6WN from "/src/images/projects/garden-art-landscapes-website.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fgarden-art-landscapes.md";
import __ASTRO_IMAGE_IMPORT_Z20Fcvi from "/src/images/projects/oak-city-shuttle-website.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Foak-city-shuttle.md";
import __ASTRO_IMAGE_IMPORT_ircGB from "/src/images/projects/zimzoom-photo-booth-website.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fzimzoom-photo-booth.md";
export default new Map([["./intro-studio.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fintro.md", __ASTRO_IMAGE_IMPORT_3JFh3], ["/src/images/projects/back-to-the-start-website.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fback-to-the-start.md", __ASTRO_IMAGE_IMPORT_Z23kbgg], ["/src/images/projects/capital-city-transportation-website.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fcapital-city-transportation.md", __ASTRO_IMAGE_IMPORT_Z1Qx4O0], ["/src/images/projects/elevated-photo-booths-website.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Felevated-photo-booths.md", __ASTRO_IMAGE_IMPORT_WTTUo], ["/src/images/projects/garden-art-landscapes-website.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fgarden-art-landscapes.md", __ASTRO_IMAGE_IMPORT_Z1Gk6WN], ["/src/images/projects/oak-city-shuttle-website.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Foak-city-shuttle.md", __ASTRO_IMAGE_IMPORT_Z20Fcvi], ["/src/images/projects/zimzoom-photo-booth-website.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fzimzoom-photo-booth.md", __ASTRO_IMAGE_IMPORT_ircGB]]);
		